# Generated by Django 5.2.7 on 2025-10-04 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(
                choices=[('admin', 'Admin'), ('seller', 'Seller'), ('guest', 'Guest')],
                default='guest',
                max_length=10
            ),
        ),
    ]
