# Generated by Django 5.2.7 on 2025-10-07 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_options_customuser_business_name_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='customuser',
            new_name='accounts_cu_email_5ce40b_idx',
            old_name='customuser_email_idx',
        ),
        migrations.RenameIndex(
            model_name='customuser',
            new_name='accounts_cu_role_666d59_idx',
            old_name='customuser_role_idx',
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
    ]
