# Generated by Django 5.2.7 on 2025-10-05 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-timestamp'], 'verbose_name_plural': 'Audit Logs'},
        ),
    ]
