# Generated by Django 5.2.7 on 2025-10-07 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_auditlog_options'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_audit_user_id_292c79_idx',
            old_name='auditlog_user_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_audit_method_717a0a_idx',
            old_name='auditlog_method_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_audit_status__b26560_idx',
            old_name='auditlog_status_idx',
        ),
    ]
