# Generated by Django 4.2 on 2025-09-30 20:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='feedback_given',
                    to=settings.AUTH_USER_MODEL
                )),
                ('seller', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='feedback_received',
                    to=settings.AUTH_USER_MODEL
                )),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='sellerfeedback',
            index=models.Index(fields=['seller'], name='sellerfeedback_seller_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerfeedback',
            index=models.Index(fields=['reviewer'], name='sellerfeedback_reviewer_idx'),
        ),
    ]
