# Generated by Django 5.2.7 on 2025-10-07 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_options'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_recipie_be3f1a_idx',
            old_name='notification_recipient_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_is_read_9edb86_idx',
            old_name='notification_isread_idx',
        ),
    ]
